import Head from "next/head";
import Image from "next/image";
import Tech from "../images/tech.png";
import DefaultLayout from "../layouts/DefaultLayout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chemotronix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main
        className="overflow-x-hidden bg-transparent text-black"
        data-theme="emerald"
      >
        <DefaultLayout>
          <div className="flex items-center justify-center bg-[#DCFFEB] py-8 mt-5 mb-5">
            <div className="flex flex-col">
              <h1 className="text-6xl font-bold">TECHNOLOGY</h1>
              <span className="text-2xl">Chemotronix web stack</span>
            </div>
          </div>
          <div className="mx-auto w-[80%] py-10 flex  gap-10 justify-center lg:flex-nowrap flex-wrap">
            <div className="flex flex-col">
              <div className="shadow rounded shadow-[#DCFFEB] bg-white px-4 z-40 py-7 border-2 border-[#DCFFEB]">
              <Image
                src={Tech}
                style={{ zIndex: -10, marginBottom: "-88px" }}
              />
              </div>
           </div>
          </div>
        </DefaultLayout>
      </main>
    </div>
  );
}
